version: '3'

services:
  temp-mysql:
    image: mysql:5.7
    container_name: temp-mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --sql-mode=''
    restart: always
    ports:
      - '9050:3306'
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: dev
      TZ: Asia/Seoul
